<div id="map">
	<div id="outposts">
		<?php if (isset($outposts)) : ?>
			<?php foreach ($outposts as $outpost) : ?>
				<div style="float:left; margin: 10px;">
					<p><?= $outpost['outpost'] ?></p>
					<a href="iis/outpost/detail/<?= $outpost['id'] ?>"><img src="iis/img/outpost.jpg"></a>
				</div>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
	<div id="map-pits">
		<?php if (isset($pits)) : ?>
			<?php foreach ($pits as $pit) : ?>
				<div style="float:left; margin: 10px;">
					<p><?= $pit['id'] ?></p>
					<a href="iis/outpost/detail/<?= $outpost['id'] ?>"><img src="iis/img/pit.jpg" width="70" height="70"></a>
				</div>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
</div>
<div id="reports">
	<?php if (!empty($expInProgress)) : ?>
		<div id="timer">
			<?php foreach($expInProgress as $i => $expedition) : ?>
				<p>
					<a href="iis/expedition/detail/<?= $expedition['id'] ?>">
						Expedition
					</a> ends in: 
					<span>
						<span  id="timer-<?= $i ?>-minutes">
							<?= floor((strtotime($expedition['finishTime']) - time())/60) ?>
						</span>
						 minutes
					</span>
					<span>
						<span  id="timer-<?= $i ?>-seconds">
							<?= (strtotime($expedition['finishTime']) - time())%60 ?>
						</span>
						 seconds
					</span>
				</p>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>
	<table>
		<tr>
			<th colspan="4">Reports</th>
		</tr>
		<?php if (!activeOutposts($outposts)) : ?>
			<tr>
				<td colspan="4">There are no active outposts, no new reports will be generated.</td>
			</tr>
		<?php endif; ?>
		<?php if (isset($reports)) : ?>
			<?php if (!empty($reports)) :   // TO DO?>
				<tr>
					<th>Date</th>
					<th>Outpost</th>
					<th>Mammoths</th>
					<th>Completion</th>
				</tr>
				<?php foreach ($reports as $report) : ?>
						<tr>
							<td><?= str_replace(' ',"<br>",$report['date']); ?></td>
							<td><a href="iis/outpost/detail/<?= $report['outpost'] ?>"><?= Outpost::getOutpostById($report['outpost'])['outpost'] ?></a></td>
							<td><?= $report['mammothCount'] ?></td>
							<?php if ($report['completion'] == '1') : ?>
								<td>
									Completed <br>
									<a href="iis/expedition/detail/<?= Report::hasExpedition($report['id'])[0]['id'] ?>">
										See Expedition <img src="iis/img/lens.png" height="15px">
									</a>
								</td>
							<?php else : ?>
								<?php if(!Report::hasExpedition($report['id'])) : ?>
									<td>
										<form method="POST" action="iis/expedition/create">
											<input type="hidden" name="report" value="<?= $report['id'] ?>">
											<input type="submit" value="Create Expedition">
										</form>
									</td>
								<?php else : ?>
									<td>
										<a href="iis/expedition/detail/<?= Report::hasExpedition($report['id'])[0]['id'] ?>">
											Expedition <br>in progress <img src="iis/img/lens.png" height="15px">
										</a>
									</td>
								<?php endif; ?>
							<?php endif; ?>
						</tr>
				<?php endforeach; ?>
			<?php else : ?>
				<tr>
					<td colspan="4">You have no reports. Try to assign some hunters to outposts.</td>
				</tr>
			<?php endif; ?>
		<?php endif; ?>
		<tr>
			<td colspan="4">
				<?php if ($_GET['page'] != 1) : ?>
					<a href="iis/home?page=<?= $_GET['page'] - 1 ?>"><</a>
				<?php endif; ?>
				<?= $_GET['page'] ?>
				<?php if (sizeof($reports)%5 == 0) : ?>
					<a href="iis/home?page=<?= $_GET['page'] + 1 ?>">></a>
				<?php endif; ?>
			</td>
		</tr>
	</table>
</div>
