<h1>Create your Hunter</h1>
<?php if (!empty($init)) : ?>
	<div id="errorMsg">
		Fill this form 4 times to create 4 hunters to start to play.
	</div>
<?php endif;?>
<form method="POST">
	<input type="text" name="hunterName" placeholder="Hunter name">
	<select name="hunterAbility">
		<?php foreach($abilities as $ability) : ?>
			<option value="<?= $ability['id'] ?>"><?= $ability['name'] ?></option>
		<?php endforeach; ?>
	</select>
	<input type="submit" value="Create">
</form>