<div class="left">
	<img src="iis/img/outpost.jpg"> 
	<p>Owner: <?= User::getUserNameById($outpost['user']); ?></p>
	<p>Name: <?= $outpost['outpost']; ?></p>
	<p>Capacity:  <?= $outpost['capacity']; ?></p>
	<p>Hunter count:  <?= $outpost['hunterCount']; ?></p>
	<hr>
	<?php if (!empty($outpostHunters)) : ?>
		<table id="availableHunters">
			<tr>
				<th colspan="4">
					Hunters at this outpost
				</th>
			</tr>
			<tr>
				<th>Name</th>
				<th>Health</th>
				<th>Ability</th>
				<th>Available</th>
			</tr>
			<?php foreach ($outpostHunters as $hunter):?>
				<tr>
					<td><?= $hunter['name'] ?></td>
					<td><?= $hunter['health'] ?></td>
					<td><?= Ability::getAbilityName($hunter['ability']) ?></td>
					<td>
					<form method="POST">
							<input type="hidden" name="removeHunter" value="<?= $hunter['id'] ?>">
							<input type="submit" value="Remove from this outpost"/>
						</form>
					</td>
				</tr>
			<?php endforeach; ?>
		</table>
	<?php else : ?>
		<table id="availableHunters">
			<tr><th>This Outpost is empty</th></tr>
		</table>
	<?php endif; ?>
</div>
<div class="right">
	<table id="availableHunters">
		<tr>
			<th colspan="4">
				My Hunters
			</th>
		</tr>
		<tr>
			<th>Name</th>
			<th>Health</th>
			<th>Ability</th>
			<th>Available</th>
		</tr>
		<?php foreach ($myHunters as $hunter):?>
			<tr>
				<td><?= $hunter['name'] ?></td>
				<td><?= $hunter['health'] ?></td>
				<td><?= Ability::getAbilityName($hunter['ability']) ?></td>
				<td>
					<?php if ($hunter['available'] == 1) : ?>
						<form method="POST">
							<input type="hidden" name="hunterId" value="<?= $hunter['id'] ?>">
							<input type="submit" value="Assign to this outpost"/>
						</form>
					<?php else : ?>
						Unavailable
					<?php endif; ?>
					
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>