<h1>Welcome</h1>
<div class="left">
	<h1>Login</h1>
	<form method="post">
		<input type="hidden" name="type" value="login">
		<input name="name" type="text" placeholder="User name" required>
		<input name="password" type="password" placeholder="Password" required>
		<input type="submit" value="Login">
	</form>
</div>
<div class="right">
	<h1>Register</h1>
	<form method="post">
		<input type="hidden" name="type" value="register">
		<input name="name" type="text" placeholder="User name" required>
		<input name="password" type="password" placeholder="Password" required>
		<input type="submit" value="Register">
	</form>
</div>