<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<title><?= $title ?></title>
		<meta name="description" content="<?= $description ?>" />
		<meta name="keywords" content="<?= $keywords ?>" />
		<link rel="stylesheet" href="iis/css/style.css" type="text/css"/>
		<link rel="stylesheet" href="iis/css/navigation.css" type="text/css"/>
		<link rel="stylesheet" href="iis/css/start.css" type="text/css"/>
		<link rel="stylesheet" href="iis/css/hunter.css" type="text/css"/>
		<link rel="stylesheet" href="iis/css/outpost.css" type="text/css"/>
		<link rel="stylesheet" href="iis/css/expedition.css" type="text/css"/>
		<script type='text/javascript' src='iis/js/expedition.js'></script>
	</head>
	<body>
		<header>
			<div class="center">
				<h1>IIS - Lovci Mamutov</h1>
			</div>
		</header>			
		<nav>
			<div class="center">
				<ul>
					<li><a href="iis/home">Home</a></li>
					<?php if (isLoggedIn()): ?>
						<li><a href="iis/hunter/overview">Hunters</a></li>
						<li><a href="iis/logout">Log out</a></li>
					<?php endif; ?>		
				</ul>
			</div>
		</nav>	
		<article>
			<div class="center">
				<?php $this->controller->writeView(); // vložení aktuálního pohledu do šablony ?>
			</div>
		</article>		
		<footer>
			<div class="center">
				<p>Rudolf Kučera (xkucer91) a Dominik Drdák (xdrdak01)</p>
			</div>
		</footer>
	</body>
</html>